### ISSUE TITLE
Spaces in filename

### ISSUE THREAD

**Issue by epa** [genehack/Git-Wrapper#82]
Git::Wrapper fails horribly if the filename contains spaces.  Yet such filenames are legal in a git repository.

Fixing this bug properly - so that all possible filenames are handled correctly - could be difficult.  But it would be an improvement to handle just space characters, perhaps by using quotation marks in the git command line.

**Comment by genehack** [comment]
So, the problem is that this will change the API. Right now, if you do something like: `$git->add('foo bar')`, that's a perfectly legal way to add the files `foo` and `bar` to the staging area. If we suddenly start janking around with the string arguments we're given based on whether or not they contain a space, I think that's opening a can of worms that will leave the code significantly more complicated, and nobody happy. 

If you wanted to provide a doc patch explaining that we don't do anything with spaces, I would be willing to look at that, but I don't think this is an area where I want to modify the existing code behavior.

**Comment by epa** [comment]
In this particular case I wanted to call `log`.  I agree, the code should not mess around with the arguments depending on whether they contain a space.  It should work the same way as git does: whether the filename contains a space or not, it should be treated as a filename.

There's also the issue of shell metacharacters which could open security holes (and if security is not a concern, at least an unpleasant bug).  Again, git itself has no problem if the filename contains `$(echo foo)`, it just treats it as a filename without any escaping bugs, and surely Git::Wrapper can hold itself to the same standard (or at least die cleanly if that's not possible).

I'll see if I can make an example patch to at least handle some more filenames in the same way as git itself handles them.

**Comment by genehack** [comment]
The problem being, all Git::Wrapper is doing is calling a shell and passing along the arguments it is given (that would be the "wrapper" part). It's the interaction of the 'git' command and the shell where your spaces are causing problems, and it's why Git::Wrapper can't do anything about it.

I think you'll find if you escape the space yourself, before calling Git::Wrapper, that things will work just fine. 

I'm not sure what code level changes you thing can be made that won't change existing behavior, because, again, somebody right now may be passing a string that looks like `"foo bar"` and expecting that to be treated like two distinct file names.

**Comment by epa** [comment]
Actually it looks like this is INVALID, and Git::Wrapper works correctly!

````
% touch 'foo bar'
% perl -Ilib -MGit::Wrapper -E '$g = new Git::Wrapper("."); $g->add("foo bar")'
% git status
[...]
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        new file:   foo bar
````

It uses IPC::Open3 internally, which means it avoids shell quoting bugs.

I don't know what I was doing wrong to get a 'horrible' failure - I will open a new bug if and when I find a case that Git::Wrapper doesn't handle correctly.
